
name: CI-CD pipeline

on:
  push:
    branches: [ "main" ]


jobs:

  job-1:
    runs-on: ubuntu-latest

    steps:

      - name: Run a one-line script of job-1
        run: echo Hello, world!



  job-2:

    runs-on: ubuntu-latest

    needs: job-1

    steps:
      - name: Run a one-line script of job-2
        run: echo Hello, world!


  job-3:

    runs-on: ubuntu-latest

    needs: job-1

    steps:
      - name: Run a one-line script of job-3
        run: echo Hello, world!



  job-4:

    runs-on: ubuntu-latest

    needs: [ job-2, job-3 ]

    steps:
      - name: Run a one-line script of job-4
        run: echo Hello, world!
